service_add_torrent:
  description: "Add a torrent to qBittorrent"
  fields:
    url:
      description: "The torrent URL to download"
      example: "http://example.com/torrent/file.torrent"
    category:
      description: "The category of the torrent"
      example: "film"
      options:
        - film
        - series
        - audio
        - app
    username:
      description: "The username for qBittorrent"
      example: "your_username"
    password:
      description: "The password for qBittorrent"
      example: "your_password"